export const content = {
  categories: [
    {
      id: "household",
      title: "🧺 Ikdienas saimnieciskie darbi",
      subtitle: "Mājas darbi / organizēšana / bērni / iepirkumi",
      description:
        "Tīrīšana, kārtošana, organizēšana, bērnu aprūpe un sadzīves atbalsts — ikdienas atvieglojums mājās.",
      icon: "🏠",
    },
    {
      id: "health",
      title: "💪 Veselība un labsajūta",
      subtitle: "Sports / relaksācija / kustība",
      description:
        "Treniņu motivācija, labsajūtas atbalsts, elpošanas prakses un kopīga kustība.",
      icon: "💚",
    },
    {
      id: "social",
      title: "🎨 Sociālais un radošais atbalsts",
      subtitle: "Sarunas / hobiji / emocionālais atbalsts",
      description:
        "Kopības brīži, sarunu biedri, emocionālais atbalsts un radošs laiks kopā.",
      icon: "🤗",
    },
    {
      id: "practical",
      title: "🧰 Praktiskie darbi Latvietim",
      subtitle: "Remonti / tehniska palīdzība / dārzs",
      description:
        "Nelieli remontdarbi, tehniska palīdzība, dārza darbi un praktiskas uzdevumu atbalsts.",
      icon: "🔧",
    },
    {
      id: "culture",
      title: "🎭 Kultūra un sabiedrība",
      subtitle: "Pasākumi / sarunas / kopīgas aktivitātes",
      description:
        "Kopīga došanās uz pasākumiem, kultūras sarunas, pavadīšana un sabiedriskās aktivitātes.",
      icon: "🎭",
    },
  ],

  helpCards: [
    {
      slug: "majas-paligs",
      categoryId: "household",
      title: "🧹 Mājas palīgs",
      description: "Palīgs, kas palīdz uzturēt mājokli kārtībā un harmonijā.",
      details: [
        "tīrīšana (putekļošana, slaucīšana, vakumēšana)",
        "skapju un skapju organizēšana",
        "veļas kārtošana, gludināšana",
        "iepirkumu palīdzība un mājas uzdevumi",
      ],
      ideal: "Ģimenes, aizņemtie profesionāļi, seniori.",
      pricing: { basic: "2h — 35 €", extended: "4h — 60 €" },
      discounts: [
        "1x nedēļā abonements –10 %",
        "Pirmais apmeklējums –15 %",
      ],
    },
    {
      slug: "skapju-kartosana",
      categoryId: "household",
      title: "🧺 Mājas organizators",
      description: "Kārtošanas un organizēšanas pakalpojumi skapjos un pieliekamos.",
      details: [
        "skapju un plauktu kārtošana",
        "etiķešu marķēšana un sistematizācija",
        "dokumentu un lietu kārtošana",
      ],
      ideal: "Ikviens, kas vēlas noturīgu kārtību.",
      pricing: { basic: "No 30 € / h" },
      discounts: ["Kombinē ar Mājas palīgu –10 %"],
    },
    {
      slug: "eko-tirisana",
      categoryId: "household",
      title: "🧴 Eko mājas tīrīšana",
      description: "Videi draudzīga tīrīšana bez agresīviem ķimikālijām.",
      details: [
        "tīrīšana ar dabīgiem līdzekļiem",
        "droši risinājumi bērniem un mājdzīvniekiem",
      ],
      ideal: "Veselības apzinīgi klienti.",
      pricing: { basic: "2h — 40 €" },
      discounts: ["Atkārtotiem klientiem –10 %"],
    },
    {
      slug: "fitnesa-draugs",
      categoryId: "health",
      title: "💪 Fitnesa draugs",
      description: "Kustību motivācija, kopīgi treniņi un aktivitātes.",
      details: [
        "vieglie treniņi vai pastaigas",
        "kustību rutīna un atbalsts",
      ],
      ideal: "Vēlies kļūt aktīvāks vai saglabāt formu.",
      pricing: { basic: "No 25 € / h" },
    },
    {
      slug: "labsajutas-atbalsts",
      categoryId: "health",
      title: "🧘 Labsajūtas atbalsts",
      description: "Elpošanas vingrinājumi, relaksācija un mierīgas prakses.",
      details: [
        "elpošanas un meditācijas prakses",
        "relaksācijas sesijas",
      ],
      ideal: "Stressa mazināšanai un labākam miegam.",
      pricing: { basic: "No 25 € / h" },
    },
    {
      slug: "emocionalais-draugs",
      categoryId: "social",
      title: "🧠 Emocionālais draugs",
      description: "Empātiskas sarunas un emocionālā klātbūtne (bez terapijas).",
      details: ["klausīšanās, sarunas par dzīvi un emocijām"],
      ideal: "Tiem, kas vēlas izrunāties vai saņemt saturīgu atbalstu.",
      pricing: { basic: "25 € / h", packages: ["4 sesijas — 85 €"] },
      discounts: ["Pirmā sesija –20 %"],
    },
    {
      slug: "radosais-partneris",
      categoryId: "social",
      title: "🎨 Radošais partneris",
      description: "Kopīgas radošas aktivitātes kā zīmēšana, mūzika, lasīšana.",
      details: ["radošās nodarbības", "kopīga kultūras pieredze"],
      ideal: "Vēlies iedvesmoties un radīt kopā.",
      pricing: { basic: "No 20 € / h" },
    },
    {
      slug: "nelieli-remontdarbi",
      categoryId: "practical",
      title: "🧰 Nelieli remontdarbi",
      description: "Nelieli mājas labojumi, mēbeļu sastiprināšana, dārza palīgs.",
      details: [
        "mēbeļu montāža un nostiprināšana",
        "sīki remontdarbi mājoklī",
      ],
      ideal: "Pasūtījumi mājokļa vajadzībām.",
      pricing: { basic: "40 € / 2h" },
      discounts: ["Kombinēts ar organizāciju –10 %"],
    },
    {
      slug: "telpu-organizesana",
      categoryId: "practical",
      title: "📦 Telpu organizēšana",
      description: "Sakārtošana garāžās, noliktavās, pieliekamos un mantas.",
      details: ["plauktu plānošana", "sistēmu izveide kārtībai"],
      ideal: "Pirms pārvākšanās vai sezonas tīrīšanas.",
      pricing: { basic: "30 € / h" },
    },
    {
      slug: "pasakumu-pavadisana",
      categoryId: "culture",
      title: "🎭 Pasākumu pavadīšana",
      description: "Kopīga došanās uz kino, teātri, koncertiem vai izstādēm.",
      details: ["plānošana, pārvadāšana, kompānija pasākumos"],
      ideal: "Vēlies drošu un patīkamu sabiedrību pasākumos.",
      pricing: { basic: "30 € / 2h" },
    },
    {
      slug: "kulturas-sarunu-biedrs",
      categoryId: "culture",
      title: "📖 Kultūras sarunu biedrs",
      description: "Sarunas par grāmatām, mākslu, vēsturi vai aktualitātēm.",
      details: ["kopīgas lasīšanas, diskusijas un domu apmaiņa"],
      ideal: "Vēlies intelektuālu dialogu un sparīgu sarunu.",
      pricing: { basic: "20 € / h" },
    },
  ],
};
